In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import load_linnerud
X, y = load_linnerud(return_X_y=True)

In [9]:
X.shape

(20, 3)

In [4]:
%%markdown

### Aperçu de l'ensemble de données
Cet ensemble de données se compose de trois exercices et de trois caractéristiques physiologiques. Ces caractéristiques ou variables sont collectées auprès de 20 hommes d'âge moyen dans un club de fitness. Ici, nous avons quelques caractéristiques de ces fonctionnalités :

Exercice (données) : Il contient 20 observations sur 3 exercices. Caractéristiques : redressements assis, mentons et sauts.
Physiologique (cible) : Il contient 20 observations sur 3 tests physiologiques. Caractéristiques : taille, poids et pouls.


### Aperçu de l'ensemble de données
Cet ensemble de données se compose de trois exercices et de trois caractéristiques physiologiques. Ces caractéristiques ou variables sont collectées auprès de 20 hommes d'âge moyen dans un club de fitness. Ici, nous avons quelques caractéristiques de ces fonctionnalités :

Exercice (données) : Il contient 20 observations sur 3 exercices. Caractéristiques : redressements assis, mentons et sauts.
Physiologique (cible) : Il contient 20 observations sur 3 tests physiologiques. Caractéristiques : taille, poids et pouls.


In [5]:
print("Exercices")
X

Exercices


array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.],
       [  4., 101.,  42.],
       [  8., 101.,  38.],
       [  6., 125.,  40.],
       [ 15., 200.,  40.],
       [ 17., 251., 250.],
       [ 17., 120.,  38.],
       [ 13., 210., 115.],
       [ 14., 215., 105.],
       [  1.,  50.,  50.],
       [  6.,  70.,  31.],
       [ 12., 210., 120.],
       [  4.,  60.,  25.],
       [ 11., 230.,  80.],
       [ 15., 225.,  73.],
       [  2., 110.,  43.]])

In [6]:
y

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.],
       [182.,  36.,  56.],
       [211.,  38.,  56.],
       [167.,  34.,  60.],
       [176.,  31.,  74.],
       [154.,  33.,  56.],
       [169.,  34.,  50.],
       [166.,  33.,  52.],
       [154.,  34.,  64.],
       [247.,  46.,  50.],
       [193.,  36.,  46.],
       [202.,  37.,  62.],
       [176.,  37.,  54.],
       [157.,  32.,  52.],
       [156.,  33.,  54.],
       [138.,  33.,  68.]])

In [7]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge

In [8]:
regr = MultiOutputRegressor(Ridge(random_state=123)).fit(X, y)
regr.predict(X[[0]])

array([[176.16484296,  35.0548407 ,  57.09000136]])